---
- name: Create a cBIP configuration for API Lab
  hosts: bigip
  connection: local

  vars:
    provider:
      password: "{{ cbip_password }}"
      server: 10.255.44.103
      user: "{{ cbip_user }}"
      validate_certs: no
      server_port: 443 

  tasks:

    - name: Create NeoSec Collector pool
      bigip_pool:
        state: present
        monitor_type: single
        monitors:
        - tcp
        provider: "{{ provider }}"
        lb_method: round-robin
        name: neosec-collector-pool
      delegate_to: localhost

    - name: Create NeoSec iRule
      bigip_irule:
        module: ltm
        name: neosec-logger
        src: files/neosec-logging.irule
        provider: "{{ provider }}"
      delegate_to: localhost

    - name: Create vAPI pool
      bigip_pool:
        state: present
        monitor_type: single
        monitors:
        - http
        provider: "{{ provider }}"
        lb_method: round-robin
        name: vapi-pool
      delegate_to: localhost

    - name: Create VAmPI ssl pool
      bigip_pool:
        state: present
        monitor_type: single
        monitors:
        - https
        provider: "{{ provider }}"
        lb_method: round-robin
        name: vampi-ssl-pool
      delegate_to: localhost

    - name: Create VAmPI non-ssl pool
      bigip_pool:
        state: present
        monitor_type: single
        monitors:
        - http
        provider: "{{ provider }}"
        lb_method: round-robin
        name: vampi-pool
      delegate_to: localhost

    - name: Create JuiceShop pool
      bigip_pool:
        state: present
        monitor_type: single
        monitors:
        - http
        provider: "{{ provider }}"
        lb_method: round-robin
        name: juiceshop-pool
      delegate_to: localhost
    
    - name: Create Hackazon pool
      bigip_pool:
        state: present
        monitor_type: single
        monitors:
        - http
        provider: "{{ provider }}"
        lb_method: round-robin
        name: hackazon-pool
      delegate_to: localhost

    - name: Create Traceable TPA pool
      bigip_pool:
        state: present
        provider: "{{ provider }}"
        lb_method: round-robin
        name: traceable-tpa-pool
      delegate_to: localhost

    - name: Add members to NeoSec Collector pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "neosec-collector {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: neosec-collector-pool
        port: 5044
      with_items:
        - host: 10.56.20.131
          name: neosec01
      delegate_to: localhost

    - name: Add members to vAPI pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: vapi-pool
        port: 80
      with_items:
        - host: 10.56.20.10
          name: ubuntusrv01
        - host: 10.56.20.11
          name: ubuntusrv02
        - host: 10.56.20.12
          name: ubuntusrv03
      delegate_to: localhost

    - name: Add members to VAmPI https pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: vampi-ssl-pool
        port: 5001
      with_items:
        - host: 10.56.20.10
          name: ubuntusrv01
        - host: 10.56.20.11
          name: ubuntusrv02
        - host: 10.56.20.12
          name: ubuntusrv03
      delegate_to: localhost

    - name: Add members to VAmPI http pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: vampi-pool
        port: 5002
      with_items:
        - host: 10.56.20.10
          name: ubuntusrv01
        - host: 10.56.20.11
          name: ubuntusrv02
        - host: 10.56.20.12
          name: ubuntusrv03
      delegate_to: localhost

    - name: Add members to Hackazon pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: hackazon-pool
        port: 9080
      with_items:
        - host: 10.56.20.10
          name: ubuntusrv01
        - host: 10.56.20.11
          name: ubuntusrv02
        - host: 10.56.20.12
          name: ubuntusrv03
      delegate_to: localhost

    - name: Add members to JuiceShop pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: juiceshop-pool
        port: 3000
      with_items:
        - host: 10.56.20.10
          name: ubuntusrv01
        - host: 10.56.20.11
          name: ubuntusrv02
        - host: 10.56.20.12
          name: ubuntusrv03
      delegate_to: localhost

    - name: Add members to Traceable TPA pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "Traceable TPA {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: traceable-tpa-pool
        port: 0
      with_items:
        - host: 10.56.20.128
          name: traceable-tpa-01
      delegate_to: localhost

    - name: Create the vAPI VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: VIP for vAPI
        destination: 10.56.10.45
        name: vapi-vip
        pool: vapi-pool
        snat: Automap
        port: 80
        clone_pools:
        - pool_name: traceable-tpa-pool
          context: serverside
        profiles:
          - mptcp-mobile-optimized
          - http
        irules:
          - neosec-logger
      delegate_to: localhost

    - name: Create the VAmPI Secure VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: VIP for crAPI
        destination: 10.56.10.45
        name: vampi-ssl-vip
        pool: vampi-ssl-pool
        port: 5001
        snat: Automap
        clone_pools:
        - pool_name: traceable-tpa-pool
          context: serverside         
        profiles:
          - mptcp-mobile-optimized
          - http
      delegate_to: localhost

    - name: Create the VAmPI Insecure VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: VIP for crAPI
        destination: 10.56.10.45
        name: vampi-vip
        pool: vampi-pool
        port: 5002
        snat: Automap
        clone_pools:
        - pool_name: traceable-tpa-pool
          context: serverside         
        profiles:
          - mptcp-mobile-optimized
          - http
        irules:
          - neosec-logger
      delegate_to: localhost

    - name: Create the Hackazon VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: VIP for Hackazon
        destination: 10.56.10.45
        name: hackazon-vip
        pool: hackazon-pool
        port: 9080
        snat: Automap
        clone_pools:
        - pool_name: traceable-tpa-pool
          context: serverside
        profiles:
          - mptcp-mobile-optimized
          - http
      delegate_to: localhost

    - name: Create the JuiceShop VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: VIP for JuiceShop
        destination: 10.56.10.45
        name: juiceshop-vip
        pool: juiceshop-pool
        port: 3000
        snat: Automap
        clone_pools:
        - pool_name: traceable-tpa-pool
          context: serverside
        profiles:
          - mptcp-mobile-optimized
          - http
      delegate_to: localhost