---
- name: Ubuntu Server Customer Jumphost Initial Config
  hosts: client_jump
  become: true
  vars_files:
    - velos_vault.yml

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: create group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add Homoney to the docker group
      ansible.builtin.user:
        name: homoneyd
        groups: docker
        append: true

    - name: Create a new regular user for Adam with sudo privileges
      user:
        name: koraba
        state: present
        groups: sudo,docker
        append: true
        create_home: true
        password: "{{ default_password }}"

    - name: Create a new regular user for <customer> with sudo privileges
      user:
        name: fanniemae
        state: present
        groups: sudo,docker
        append: true
        create_home: true
        password: "{{ default_password }}"


    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - gnupg2
          - vim
          - git
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Add Terraform/Hashicorp GPG apt Key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add Terraform Repository
      apt_repository:
        repo: deb https://apt.releases.hashicorp.com jammy main
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Update apt and install docker-compose
      apt:
        name: docker-compose
        state: latest
        update_cache: false

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install terraform
      apt:
        name: terraform
        state: latest
        update_cache: false

