---
- hosts: centos
  become: true

  tasks:

  - name: Creating subfolders
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - /tmp/neosec

  - name: Download foo.conf
    ansible.builtin.get_url:
      url: https://artifacts.neosec.com/installer/node-installer
      dest: /tmp/neosec/installer
      mode: '0744'

  - name: Run NeoSec installer
    ansible.builtin.command: "installer install yum -username {{ neosec_username|quote }} -password {{ neosec_password|quote }} -source-id {{ neosec_source_id|quote }} -collector-name {{ neosec_collector_name|quote }}"